### ISSUE TITLE
Testing phase

### ISSUE THREAD

**Issue by Taknax** [FlashHUN/FlashNPCs#20]
I am testing FNPCs and it runs very well. Some small issues i am dealing with.

1. If combined with Gender mod [https://www.curseforge.com/minecraft/mc-mods/gender](url), the npc's occure only as woman gender. (they have breasts).
![2022-04-05_20 43 14](https://user-images.githubusercontent.com/66703017/161827231-67485e3b-cc7c-4306-9d33-c950af71b943.png)

3. Could not figure out how to write the path for custom skins. I put skin png's in the following directory:  ".minecraft\config\x\skins\".
Could you tell me how the path have to look like?

4. I have a idea for the close button for players. Maybe you can make a bottun as ESC hotkey. That would solve it.

**Comment by FlashHUN** [comment]
> If combined with Gender mod, the npc's occure only as woman gender. (they have breasts).

If I had to guess (since it isn't open source) the gender mod uses mixins to add its stuff to the player model, and they have some sort of data tags (either a capability or nbt) added to the player to save their gender data. If it's nbt, you can use the /data command to set it, otherwise there's not much that can be done. Compatibility with other mods unless it's something game breaking is on the bottom of my priority list until I'm done with most features.

> Could not figure out how to write the path for custom skins. I put skin png's in the following directory: ".minecraft\config\x\skins".
Could you tell me how the path have to look like?

You need to use a link to an image. People on the discord recommend using [MineSkin](https://mineskin.org/). Resource Pack support will come in the next update! ^^

> I have a idea for the close button for players. Maybe you can make a bottun as ESC hotkey. That would solve it.

Close button for players? What? You can already close all guis with ESC, that's just how Minecraft works... What did you mean?

**Comment by Taknax** [comment]
"Close button for players? What? You can already close all guis with ESC, that's just how Minecraft works... What did you mean?"

If i open dialogue and read it. I have to click ESC to close the dialogue window. Thats totally nice. To higher gameplay, you could make a button additionally, to close the dialogue. So i could decide, i want to use ESC or the close button.
For the close button, you said its abit complicated. My idea is: make a button which trigger ESC (also not a close function just a hotkey trigger function) by pressing. Sry for my english. I am using translator. This is not a issue or so. Would make the gameplay even better.

**Comment by Taknax** [comment]
"You need to use a link to an image. People on the discord recommend using [MineSkin](https://mineskin.org/). Resource Pack support will come in the next update! ^^"

That is super cool, but mineskin doesnt work so good. I know taterzens use it too, but i occured bigger issues there.
I hope i can use easily imgur. that would be amazing.

**Comment by Taknax** [comment]
"If I had to guess (since it isn't open source) the gender mod uses mixins to add its stuff to the player model, and they have some sort of data tags (either a capability or nbt) added to the player to save their gender data. If it's nbt, you can use the /data command to set it, otherwise there's not much that can be done. Compatibility with other mods unless it's something game breaking is on the bottom of my priority list until I'm done with most features."

Nice to hear. I would test it more and more and deeper and deeper. Atm it is on a modpack with 200+ mods and runs like charm. nearly 0 Performance consuming. Thats really great. I would tell you my founds in discord. thats esasier for me to communicate.
